<?php
/**
 * currencies declaration
 */
return array (
'AED' => array ( 'numeric_code'  =>	784	, 'code' => 'AED', 'name' => t('United Arab Emirates dirham'),  'symbol' => 'د.إ', 'fraction_name' => t('Fils'), 'decimals' => 2 ),
'AFN' => array ( 'numeric_code'  =>	971	, 'code' => 'AFN', 'name' => t('Afghan afghani'),               'symbol' => '؋', 'fraction_name' => t('Pul'), 'decimals' => 2 ),
'ALL' => array ( 'numeric_code'  =>	8	  , 'code' => 'ALL', 'name' => t('Albanian lek'),                 'symbol' => 'L', 'fraction_name' => t('Qintar'), 'decimals' => 2 ),
'AMD' => array ( 'numeric_code'  =>	51	, 'code' => 'AMD', 'name' => t('Armenian dram'),                'symbol' => 'դր.', 'fraction_name' => t('Luma'), 'decimals' => 2 ),
'ANG' => array ( 'numeric_code'  =>	532	, 'code' => 'ANG', 'name' => t('Netherlands Antillean guilder'),  'symbol' => 'ƒ', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'AOA' => array ( 'numeric_code'  =>	973	, 'code' => 'AOA', 'name' => t('Angolan kwanza'),                 'symbol' => 'Kz', 'fraction_name' => t('Cêntimo'), 'decimals' => 2 ),
'ARS' => array ( 'numeric_code'  =>	32	, 'code' => 'ARS', 'name' => t('Argentine peso'),                 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'AUD' => array ( 'numeric_code'  =>	36	, 'code' => 'AUD', 'name' => t('Australian dollar'),              'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'AWG' => array ( 'numeric_code'  =>	533	, 'code' => 'AWG', 'name' => t('Aruban florin'), 'symbol' => 'ƒ', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'AZN' => array ( 'numeric_code'  =>	944	, 'code' => 'AZN', 'name' => t('Azerbaijani manat'), 'symbol' => 'AZN', 'fraction_name' => t('Qəpik'), 'decimals' => 2 ),
'BAM' => array ( 'numeric_code'  =>	977	, 'code' => 'BAM', 'name' => t('Bosnia and Herzegovina convertible mark'), 'symbol' => 'КМ', 'fraction_name' => t('Fening'), 'decimals' => 2 ),
'BBD' => array ( 'numeric_code'  =>	52	, 'code' => 'BBD', 'name' => t('Barbadian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'BDT' => array ( 'numeric_code'  =>	50	, 'code' => 'BDT', 'name' => t('Bangladeshi taka'), 'symbol' => '৳', 'fraction_name' => t('Paisa'), 'decimals' => 2 ),
'BGN' => array ( 'numeric_code'  =>	975	, 'code' => 'BGN', 'name' => t('Bulgarian lev'), 'symbol' => 'лв', 'fraction_name' => t('Stotinka'), 'decimals' => 2 ),
'BHD' => array ( 'numeric_code'  =>	48	, 'code' => 'BHD', 'name' => t('Bahraini dinar'), 'symbol' => 'ب.د', 'fraction_name' => t('Fils'), 'decimals' => 3 ),
'BIF' => array ( 'numeric_code'  =>	108	, 'code' => 'BIF', 'name' => t('Burundian franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'BMD' => array ( 'numeric_code'  =>	60	, 'code' => 'BMD', 'name' => t('Bermudian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'BND' => array ( 'numeric_code'  =>	96	, 'code' => 'BND', 'name' => t('Brunei dollar'), 'symbol' => '$', 'fraction_name' => t('Sen'), 'decimals' => 2 ),
'BOB' => array ( 'numeric_code'  =>	68	, 'code' => 'BOB', 'name' => t('Bolivian boliviano'), 'symbol' => 'Bs.', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'BRL' => array ( 'numeric_code'  =>	986	, 'code' => 'BRL', 'name' => t('Brazilian real'), 'symbol' => 'R$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'BSD' => array ( 'numeric_code'  =>	44	, 'code' => 'BSD', 'name' => t('Bahamian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'BTN' => array ( 'numeric_code'  =>	64	, 'code' => 'BTN', 'name' => t('Bhutanese ngultrum'), 'symbol' => 'BTN', 'fraction_name' => t('Chertrum'), 'decimals' => 2 ),
'BWP' => array ( 'numeric_code'  =>	72	, 'code' => 'BWP', 'name' => t('Botswana pula'), 'symbol' => 'P', 'fraction_name' => t('Thebe'), 'decimals' => 2 ),
'BYR' => array ( 'numeric_code'  =>	974	, 'code' => 'BYR', 'name' => t('Belarusian ruble'), 'symbol' => 'Br', 'fraction_name' => t('Kapyeyka'), 'decimals' => 2 ),
'BZD' => array ( 'numeric_code'  =>	84	, 'code' => 'BZD', 'name' => t('Belize dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'CAD' => array ( 'numeric_code'  =>	124	, 'code' => 'CAD', 'name' => t('Canadian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'CDF' => array ( 'numeric_code'  =>	976	, 'code' => 'CDF', 'name' => t('Congolese franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'CHF' => array ( 'numeric_code'  =>	756	, 'code' => 'CHF', 'name' => t('Swiss franc'), 'symbol' => 'Fr', 'fraction_name' => t('Rappen[I]'), 'decimals' => 2 ),
'CLP' => array ( 'numeric_code'  =>	152	, 'code' => 'CLP', 'name' => t('Chilean peso'), 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'CNY' => array ( 'numeric_code'  =>	156	, 'code' => 'CNY', 'name' => t('Chinese yuan'), 'symbol' => '元', 'fraction_name' => t('Fen[E]'), 'decimals' => 2 ),
'COP' => array ( 'numeric_code'  =>	170	, 'code' => 'COP', 'name' => t('Colombian peso'), 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'CRC' => array ( 'numeric_code'  =>	188	, 'code' => 'CRC', 'name' => t('Costa Rican colón'), 'symbol' => '₡', 'fraction_name' => t('Céntimo'), 'decimals' => 2 ),
'CUC' => array ( 'numeric_code'  =>	931	, 'code' => 'CUC', 'name' => t('Cuban convertible peso'), 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'CUP' => array ( 'numeric_code'  =>	192	, 'code' => 'CUP', 'name' => t('Cuban peso'), 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'CVE' => array ( 'numeric_code'  =>	132	, 'code' => 'CVE', 'name' => t('Cape Verdean escudo'), 'symbol' => 'Esc', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'CZK' => array ( 'numeric_code'  =>	203	, 'code' => 'CZK', 'name' => t('Czech koruna'), 'symbol' => 'Kč', 'fraction_name' => t('Haléř'), 'decimals' => 2 ),
'DJF' => array ( 'numeric_code'  =>	262	, 'code' => 'DJF', 'name' => t('Djiboutian franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'DKK' => array ( 'numeric_code'  =>	208	, 'code' => 'DKK', 'name' => t('Danish krone'), 'symbol' => 'kr', 'fraction_name' => t('Øre'), 'decimals' => 2 ),
'DOP' => array ( 'numeric_code'  =>	214	, 'code' => 'DOP', 'name' => t('Dominican peso'), 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'DZD' => array ( 'numeric_code'  =>	12	, 'code' => 'DZD', 'name' => t('Algerian dinar'), 'symbol' => 'د.ج', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'EEK' => array ( 'numeric_code'  =>	233	, 'code' => 'EEK', 'name' => t('Estonian kroon'), 'symbol' => 'KR', 'fraction_name' => t('Sent'), 'decimals' => 2 ),
'EGP' => array ( 'numeric_code'  =>	818	, 'code' => 'EGP', 'name' => t('Egyptian pound'), 'symbol' => '£', 'fraction_name' => t('Piastre[F]'), 'decimals' => 2 ),
'ERN' => array ( 'numeric_code'  =>	232	, 'code' => 'ERN', 'name' => t('Eritrean nakfa'), 'symbol' => 'Nfk', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'ETB' => array ( 'numeric_code'  =>	230	, 'code' => 'ETB', 'name' => t('Ethiopian birr'), 'symbol' => 'ETB', 'fraction_name' => t('Santim'), 'decimals' => 2 ),
'EUR' => array ( 'numeric_code'  =>	978	, 'code' => 'EUR', 'name' => t('Euro'), 'symbol' => '€', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'FJD' => array ( 'numeric_code'  =>	242	, 'code' => 'FJD', 'name' => t('Fijian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'FKP' => array ( 'numeric_code'  =>	238	, 'code' => 'FKP', 'name' => t('Falkland Islands pound'), 'symbol' => '£', 'fraction_name' => t('Penny'), 'decimals' => 2 ),
'GBP' => array ( 'numeric_code'  =>	826	, 'code' => 'GBP', 'name' => t('British pound[C]'), 'symbol' => '£', 'fraction_name' => t('Penny'), 'decimals' => 2 ),
'GEL' => array ( 'numeric_code'  =>	981	, 'code' => 'GEL', 'name' => t('Georgian lari'), 'symbol' => 'ლ', 'fraction_name' => t('Tetri'), 'decimals' => 2 ),
'GHS' => array ( 'numeric_code'  =>	936	, 'code' => 'GHS', 'name' => t('Ghanaian cedi'), 'symbol' => '₵', 'fraction_name' => t('Pesewa'), 'decimals' => 2 ),
'GIP' => array ( 'numeric_code'  =>	292	, 'code' => 'GIP', 'name' => t('Gibraltar pound'), 'symbol' => '£', 'fraction_name' => t('Penny'), 'decimals' => 2 ),
'GMD' => array ( 'numeric_code'  =>	270	, 'code' => 'GMD', 'name' => t('Gambian dalasi'), 'symbol' => 'D', 'fraction_name' => t('Butut'), 'decimals' => 2 ),
'GNF' => array ( 'numeric_code'  =>	324	, 'code' => 'GNF', 'name' => t('Guinean franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'GTQ' => array ( 'numeric_code'  =>	320	, 'code' => 'GTQ', 'name' => t('Guatemalan quetzal'), 'symbol' => 'Q', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'GYD' => array ( 'numeric_code'  =>	328	, 'code' => 'GYD', 'name' => t('Guyanese dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'HKD' => array ( 'numeric_code'  =>	344	, 'code' => 'HKD', 'name' => t('Hong Kong dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'HNL' => array ( 'numeric_code'  =>	340	, 'code' => 'HNL', 'name' => t('Honduran lempira'), 'symbol' => 'L', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'HRK' => array ( 'numeric_code'  =>	191	, 'code' => 'HRK', 'name' => t('Croatian kuna'), 'symbol' => 'kn', 'fraction_name' => t('Lipa'), 'decimals' => 2 ),
'HTG' => array ( 'numeric_code'  =>	332	, 'code' => 'HTG', 'name' => t('Haitian gourde'), 'symbol' => 'G', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'HUF' => array ( 'numeric_code'  =>	348	, 'code' => 'HUF', 'name' => t('Hungarian forint'), 'symbol' => 'Ft', 'fraction_name' => t('Fillér'), 'decimals' => 2 ),
'IDR' => array ( 'numeric_code'  =>	360	, 'code' => 'IDR', 'name' => t('Indonesian rupiah'), 'symbol' => 'Rp', 'fraction_name' => t('Sen'), 'decimals' => 2 ),
'ILS' => array ( 'numeric_code'  =>	376	, 'code' => 'ILS', 'name' => t('Israeli new sheqel'), 'symbol' => '₪', 'fraction_name' => t('Agora'), 'decimals' => 2 ),
'INR' => array ( 'numeric_code'  =>	356	, 'code' => 'INR', 'name' => t('Indian rupee'), 'symbol' => '₨', 'fraction_name' => t('Paisa'), 'decimals' => 2 ),
'IQD' => array ( 'numeric_code'  =>	368	, 'code' => 'IQD', 'name' => t('Iraqi dinar'), 'symbol' => 'ع.د', 'fraction_name' => t('Fils'), 'decimals' => 3 ),
'IRR' => array ( 'numeric_code'  =>	364	, 'code' => 'IRR', 'name' => t('Iranian rial'), 'symbol' => '﷼', 'fraction_name' => t('Dinar'), 'decimals' => 2 ),
'ISK' => array ( 'numeric_code'  =>	352	, 'code' => 'ISK', 'name' => t('Icelandic króna'), 'symbol' => 'kr', 'fraction_name' => t('Eyrir'), 'decimals' => 2 ),
'JMD' => array ( 'numeric_code'  =>	388	, 'code' => 'JMD', 'name' => t('Jamaican dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'JOD' => array ( 'numeric_code'  =>	400	, 'code' => 'JOD', 'name' => t('Jordanian dinar'), 'symbol' => 'د.ا', 'fraction_name' => t('Piastre[H]'), 'decimals' => 2 ),
'JPY' => array ( 'numeric_code'  =>	392	, 'code' => 'JPY', 'name' => t('Japanese yen'), 'symbol' => '¥', 'fraction_name' => t('Sen[G]'), 'decimals' => 2 ),
'KES' => array ( 'numeric_code'  =>	404	, 'code' => 'KES', 'name' => t('Kenyan shilling'), 'symbol' => 'Sh', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'KGS' => array ( 'numeric_code'  =>	417	, 'code' => 'KGS', 'name' => t('Kyrgyzstani som'), 'symbol' => 'KGS', 'fraction_name' => t('Tyiyn'), 'decimals' => 2 ),
'KHR' => array ( 'numeric_code'  =>	116	, 'code' => 'KHR', 'name' => t('Cambodian riel'), 'symbol' => '៛', 'fraction_name' => t('Sen'), 'decimals' => 2 ),
'KMF' => array ( 'numeric_code'  =>	174	, 'code' => 'KMF', 'name' => t('Comorian franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'KPW' => array ( 'numeric_code'  =>	408	, 'code' => 'KPW', 'name' => t('North Korean won'), 'symbol' => '₩', 'fraction_name' => t('Chŏn'), 'decimals' => 2 ),
'KRW' => array ( 'numeric_code'  =>	410	, 'code' => 'KRW', 'name' => t('South Korean won'), 'symbol' => '₩', 'fraction_name' => t('Jeon'), 'decimals' => 2 ),
'KWD' => array ( 'numeric_code'  =>	414	, 'code' => 'KWD', 'name' => t('Kuwaiti dinar'), 'symbol' => 'د.ك', 'fraction_name' => t('Fils'), 'decimals' => 3 ),
'KYD' => array ( 'numeric_code'  =>	136	, 'code' => 'KYD', 'name' => t('Cayman Islands dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'KZT' => array ( 'numeric_code'  =>	398	, 'code' => 'KZT', 'name' => t('Kazakhstani tenge'), 'symbol' => '〒', 'fraction_name' => t('Tiyn'), 'decimals' => 2 ),
'LAK' => array ( 'numeric_code'  =>	418	, 'code' => 'LAK', 'name' => t('Lao kip'), 'symbol' => '₭', 'fraction_name' => t('Att'), 'decimals' => 2 ),
'LBP' => array ( 'numeric_code'  =>	422	, 'code' => 'LBP', 'name' => t('Lebanese pound'), 'symbol' => 'ل.ل', 'fraction_name' => t('Piastre'), 'decimals' => 2 ),
'LKR' => array ( 'numeric_code'  =>	144	, 'code' => 'LKR', 'name' => t('Sri Lankan rupee'), 'symbol' => 'Rs', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'LRD' => array ( 'numeric_code'  =>	430	, 'code' => 'LRD', 'name' => t('Liberian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'LSL' => array ( 'numeric_code'  =>	426	, 'code' => 'LSL', 'name' => t('Lesotho loti'), 'symbol' => 'L', 'fraction_name' => t('Sente'), 'decimals' => 2 ),
'LTL' => array ( 'numeric_code'  =>	440	, 'code' => 'LTL', 'name' => t('Lithuanian litas'), 'symbol' => 'Lt', 'fraction_name' => t('Centas'), 'decimals' => 2 ),
'LVL' => array ( 'numeric_code'  =>	428	, 'code' => 'LVL', 'name' => t('Latvian lats'), 'symbol' => 'Ls', 'fraction_name' => t('Santīms'), 'decimals' => 2 ),
'LYD' => array ( 'numeric_code'  =>	434	, 'code' => 'LYD', 'name' => t('Libyan dinar'), 'symbol' => 'ل.د', 'fraction_name' => t('Dirham'), 'decimals' => 3 ),
'MAD' => array ( 'numeric_code'  =>	504	, 'code' => 'MAD', 'name' => t('Moroccan dirham'), 'symbol' => 'Dh', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'MDL' => array ( 'numeric_code'  =>	498	, 'code' => 'MDL', 'name' => t('Moldovan leu'), 'symbol' => 'L', 'fraction_name' => t('Ban'), 'decimals' => 2 ),
'MGA' => array ( 'numeric_code'  =>	969	, 'code' => 'MGA', 'name' => t('Malagasy ariary'), 'symbol' => 'MGA', 'fraction_name' => t('Iraimbilanja'), 'decimals' =>	5	),
'MKD' => array ( 'numeric_code'  =>	807	, 'code' => 'MKD', 'name' => t('Macedonian denar'), 'symbol' => 'ден', 'fraction_name' => t('Deni'), 'decimals' => 2 ),
'MMK' => array ( 'numeric_code'  =>	104	, 'code' => 'MMK', 'name' => t('Myanma kyat'), 'symbol' => 'K', 'fraction_name' => t('Pya'), 'decimals' => 2 ),
'MNT' => array ( 'numeric_code'  =>	496	, 'code' => 'MNT', 'name' => t('Mongolian tögrög'), 'symbol' => '₮', 'fraction_name' => t('Möngö'), 'decimals' => 2 ),
'MOP' => array ( 'numeric_code'  =>	446	, 'code' => 'MOP', 'name' => t('Macanese pataca'), 'symbol' => 'P', 'fraction_name' => t('Avo'), 'decimals' => 2 ),
'MRO' => array ( 'numeric_code'  =>	478	, 'code' => 'MRO', 'name' => t('Mauritanian ouguiya'), 'symbol' => 'UM', 'fraction_name' => t('Khoums'), 'decimals' =>	5	),
'MUR' => array ( 'numeric_code'  =>	480	, 'code' => 'MUR', 'name' => t('Mauritian rupee'), 'symbol' => '₨', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'MVR' => array ( 'numeric_code'  =>	462	, 'code' => 'MVR', 'name' => t('Maldivian rufiyaa'), 'symbol' => 'ރ.', 'fraction_name' => t('Laari'), 'decimals' => 2 ),
'MWK' => array ( 'numeric_code'  =>	454	, 'code' => 'MWK', 'name' => t('Malawian kwacha'), 'symbol' => 'MK', 'fraction_name' => t('Tambala'), 'decimals' => 2 ),
'MXN' => array ( 'numeric_code'  =>	484	, 'code' => 'MXN', 'name' => t('Mexican peso'), 'symbol' => '$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'MYR' => array ( 'numeric_code'  =>	458	, 'code' => 'MYR', 'name' => t('Malaysian ringgit'), 'symbol' => 'RM', 'fraction_name' => t('Sen'), 'decimals' => 2 ),
'MZN' => array ( 'numeric_code'  =>	943	, 'code' => 'MZN', 'name' => t('Mozambican metical'), 'symbol' => 'MTn', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'NAD' => array ( 'numeric_code'  =>	516	, 'code' => 'NAD', 'name' => t('Namibian dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'NGN' => array ( 'numeric_code'  =>	566	, 'code' => 'NGN', 'name' => t('Nigerian naira'), 'symbol' => '₦', 'fraction_name' => t('Kobo'), 'decimals' => 2 ),
'NIO' => array ( 'numeric_code'  =>	558	, 'code' => 'NIO', 'name' => t('Nicaraguan córdoba'), 'symbol' => 'C$', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'NOK' => array ( 'numeric_code'  =>	578	, 'code' => 'NOK', 'name' => t('Norwegian krone'), 'symbol' => 'kr', 'fraction_name' => t('Øre'), 'decimals' => 2 ),
'NPR' => array ( 'numeric_code'  =>	524	, 'code' => 'NPR', 'name' => t('Nepalese rupee'), 'symbol' => '₨', 'fraction_name' => t('Paisa'), 'decimals' => 2 ),
'NZD' => array ( 'numeric_code'  =>	554	, 'code' => 'NZD', 'name' => t('New Zealand dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'OMR' => array ( 'numeric_code'  =>	512	, 'code' => 'OMR', 'name' => t('Omani rial'), 'symbol' => 'ر.ع.', 'fraction_name' => t('Baisa'), 'decimals' => 3 ),
'PAB' => array ( 'numeric_code'  =>	590	, 'code' => 'PAB', 'name' => t('Panamanian balboa'), 'symbol' => 'B/.', 'fraction_name' => t('Centésimo'), 'decimals' => 2 ),
'PEN' => array ( 'numeric_code'  =>	604	, 'code' => 'PEN', 'name' => t('Peruvian nuevo sol'), 'symbol' => 'S/.', 'fraction_name' => t('Céntimo'), 'decimals' => 2 ),
'PGK' => array ( 'numeric_code'  =>	598	, 'code' => 'PGK', 'name' => t('Papua New Guinean kina'), 'symbol' => 'K', 'fraction_name' => t('Toea'), 'decimals' => 2 ),
'PHP' => array ( 'numeric_code'  =>	608	, 'code' => 'PHP', 'name' => t('Philippine peso'), 'symbol' => '₱', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'PKR' => array ( 'numeric_code'  =>	586	, 'code' => 'PKR', 'name' => t('Pakistani rupee'), 'symbol' => '₨', 'fraction_name' => t('Paisa'), 'decimals' => 2 ),
'PLN' => array ( 'numeric_code'  =>	985	, 'code' => 'PLN', 'name' => t('Polish złoty'), 'symbol' => 'zł', 'fraction_name' => t('Grosz'), 'decimals' => 2 ),
'PYG' => array ( 'numeric_code'  =>	600	, 'code' => 'PYG', 'name' => t('Paraguayan guaraní'), 'symbol' => '₲', 'fraction_name' => t('Céntimo'), 'decimals' => 2 ),
'QAR' => array ( 'numeric_code'  =>	634	, 'code' => 'QAR', 'name' => t('Qatari riyal'), 'symbol' => 'ر.ق', 'fraction_name' => t('Dirham'), 'decimals' => 2 ),
'RON' => array ( 'numeric_code'  =>	946	, 'code' => 'RON', 'name' => t('Romanian leu'), 'symbol' => 'L', 'fraction_name' => t('Ban'), 'decimals' => 2 ),
'RSD' => array ( 'numeric_code'  =>	941	, 'code' => 'RSD', 'name' => t('Serbian dinar'), 'symbol' => 'дин.', 'fraction_name' => t('Para'), 'decimals' => 2 ),
'RUB' => array ( 'numeric_code'  =>	643	, 'code' => 'RUB', 'name' => t('Russian ruble'), 'symbol' => 'руб.', 'fraction_name' => t('Kopek'), 'decimals' => 2 ),
'RWF' => array ( 'numeric_code'  =>	646	, 'code' => 'RWF', 'name' => t('Rwandan franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'SAR' => array ( 'numeric_code'  =>	682	, 'code' => 'SAR', 'name' => t('Saudi riyal'), 'symbol' => 'ر.س', 'fraction_name' => t('Hallallah'), 'decimals' => 2 ),
'SBD' => array ( 'numeric_code'  =>	90	, 'code' => 'SBD', 'name' => t('Solomon Islands dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'SCR' => array ( 'numeric_code'  =>	690	, 'code' => 'SCR', 'name' => t('Seychellois rupee'), 'symbol' => '₨', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'SDG' => array ( 'numeric_code'  =>	938	, 'code' => 'SDG', 'name' => t('Sudanese pound'), 'symbol' => '£', 'fraction_name' => t('Piastre'), 'decimals' => 2 ),
'SEK' => array ( 'numeric_code'  =>	752	, 'code' => 'SEK', 'name' => t('Swedish krona'), 'symbol' => 'kr', 'fraction_name' => t('Öre'), 'decimals' => 2 ),
'SGD' => array ( 'numeric_code'  =>	702	, 'code' => 'SGD', 'name' => t('Singapore dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'SHP' => array ( 'numeric_code'  =>	654	, 'code' => 'SHP', 'name' => t('Saint Helena pound'), 'symbol' => '£', 'fraction_name' => t('Penny'), 'decimals' => 2 ),
'SLL' => array ( 'numeric_code'  =>	694	, 'code' => 'SLL', 'name' => t('Sierra Leonean leone'), 'symbol' => 'Le', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'SOS' => array ( 'numeric_code'  =>	706	, 'code' => 'SOS', 'name' => t('Somali shilling'), 'symbol' => 'Sh', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'SRD' => array ( 'numeric_code'  =>	968	, 'code' => 'SRD', 'name' => t('Surinamese dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'STD' => array ( 'numeric_code'  =>	678	, 'code' => 'STD', 'name' => t('São Tomé and Príncipe dobra'), 'symbol' => 'Db', 'fraction_name' => t('Cêntimo'), 'decimals' => 2 ),
'SVC' => array ( 'numeric_code'  =>	222	, 'code' => 'SVC', 'name' => t('Salvadoran colón'), 'symbol' => '₡', 'fraction_name' => t('Centavo'), 'decimals' => 2 ),
'SYP' => array ( 'numeric_code'  =>	760	, 'code' => 'SYP', 'name' => t('Syrian pound'), 'symbol' => '£', 'fraction_name' => t('Piastre'), 'decimals' => 2 ),
'SZL' => array ( 'numeric_code'  =>	748	, 'code' => 'SZL', 'name' => t('Swazi lilangeni'), 'symbol' => 'L', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'THB' => array ( 'numeric_code'  =>	764	, 'code' => 'THB', 'name' => t('Thai baht'), 'symbol' => '฿', 'fraction_name' => t('Satang'), 'decimals' => 2 ),
'TJS' => array ( 'numeric_code'  =>	972	, 'code' => 'TJS', 'name' => t('Tajikistani somoni'), 'symbol' => 'ЅМ', 'fraction_name' => t('Diram'), 'decimals' => 2 ),
'TMM' => array ( 'numeric_code'  =>	0	  , 'code' => 'TMM', 'name' => t('Turkmenistani manat'), 'symbol' => 'm', 'fraction_name' => t('Tennesi'), 'decimals' => 2 ),
'TND' => array ( 'numeric_code'  =>	788	, 'code' => 'TND', 'name' => t('Tunisian dinar'), 'symbol' => 'د.ت', 'fraction_name' => t('Millime'), 'decimals' => 3 ),
'TOP' => array ( 'numeric_code'  =>	776	, 'code' => 'TOP', 'name' => t('Tongan paʻanga'), 'symbol' => 'T$', 'fraction_name' => t('Seniti[J]'), 'decimals' => 2 ),
'TRY' => array ( 'numeric_code'  =>	949	, 'code' => 'TRY', 'name' => t('Turkish lira'), 'symbol' => 'TL', 'fraction_name' => t('Kuruş'), 'decimals' => 2 ),
'TTD' => array ( 'numeric_code'  =>	780	, 'code' => 'TTD', 'name' => t('Trinidad and Tobago dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'TWD' => array ( 'numeric_code'  =>	901	, 'code' => 'TWD', 'name' => t('New Taiwan dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'TZS' => array ( 'numeric_code'  =>	834	, 'code' => 'TZS', 'name' => t('Tanzanian shilling'), 'symbol' => 'Sh', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'UAH' => array ( 'numeric_code'  =>	980	, 'code' => 'UAH', 'name' => t('Ukrainian hryvnia'), 'symbol' => '₴', 'fraction_name' => t('Kopiyka'), 'decimals' => 2 ),
'UGX' => array ( 'numeric_code'  =>	800	, 'code' => 'UGX', 'name' => t('Ugandan shilling'), 'symbol' => 'Sh', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'USD' => array ( 'numeric_code'  =>	840	, 'code' => 'USD', 'name' => t('United States dollar'), 'symbol' => '$', 'fraction_name' => t('Cent[D]'), 'decimals' => 2 ),
'UYU' => array ( 'numeric_code'  =>	858	, 'code' => 'UYU', 'name' => t('Uruguayan peso'), 'symbol' => '$', 'fraction_name' => t('Centésimo'), 'decimals' => 2 ),
'UZS' => array ( 'numeric_code'  =>	860	, 'code' => 'UZS', 'name' => t('Uzbekistani som'), 'symbol' => 'UZS', 'fraction_name' => t('Tiyin'), 'decimals' => 2 ),
'VEF' => array ( 'numeric_code'  =>	937	, 'code' => 'VEF', 'name' => t('Venezuelan bolívar'), 'symbol' => 'Bs F', 'fraction_name' => t('Céntimo'), 'decimals' => 2 ),
'VND' => array ( 'numeric_code'  =>	704	, 'code' => 'VND', 'name' => t('Vietnamese đồng'), 'symbol' => '₫', 'fraction_name' => t('Hào[K]'), 'decimals' =>	10	),
'VUV' => array ( 'numeric_code'  =>	548	, 'code' => 'VUV', 'name' => t('Vanuatu vatu'), 'symbol' => 'Vt', 'fraction_name' => t('None'), 'decimals' => NULL ),
'WST' => array ( 'numeric_code'  =>	882	, 'code' => 'WST', 'name' => t('Samoan tala'), 'symbol' => 'T', 'fraction_name' => t('Sene'), 'decimals' => 2 ),
'XAF' => array ( 'numeric_code'  =>	950	, 'code' => 'XAF', 'name' => t('Central African CFA franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'XCD' => array ( 'numeric_code'  =>	951	, 'code' => 'XCD', 'name' => t('East Caribbean dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'XOF' => array ( 'numeric_code'  =>	952	, 'code' => 'XOF', 'name' => t('West African CFA franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'XPF' => array ( 'numeric_code'  =>	953	, 'code' => 'XPF', 'name' => t('CFP franc'), 'symbol' => 'Fr', 'fraction_name' => t('Centime'), 'decimals' => 2 ),
'YER' => array ( 'numeric_code'  =>	886	, 'code' => 'YER', 'name' => t('Yemeni rial'), 'symbol' => '﷼', 'fraction_name' => t('Fils'), 'decimals' => 2 ),
'ZAR' => array ( 'numeric_code'  =>	710	, 'code' => 'ZAR', 'name' => t('South African rand'), 'symbol' => 'R', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
'ZMK' => array ( 'numeric_code'  =>	894	, 'code' => 'ZMK', 'name' => t('Zambian kwacha'), 'symbol' => 'ZK', 'fraction_name' => t('Ngwee'), 'decimals' => 2 ),
'ZWR' => array ( 'numeric_code'  =>	0	, 'code' => 'ZWR', 'name' => t('Zimbabwean dollar'), 'symbol' => '$', 'fraction_name' => t('Cent'), 'decimals' => 2 ),
);
/**
 * return string
 * @param $string
 * @return mixed
 */
function t($string){
    return $string;
}
?>